### ISSUE TITLE
"Request for current state update"

### ISSUE THREAD

**Issue by jharvey83** [joe-ng/homebridge-dyson-link#10]
Plugin loads OK, appears to create all the devices. However, I see a persistent:

```
Nov  5 20:33:22 raspberrypi homebridge[5227]: [2017-11-5 20:33:22] [DysonPlatform] Request for current state update
```

It looks like the request from the Home app then times out (as this appears not to return) rendering all devices as No Response.

Running node 8.9, home bridge 0.4.31, iOS 11.1

**Comment by joe-ng** [comment]
Did you see any log about {"msg": "CURRENT-STATE",  ...} ?
If not, maybe the request was blocked by your router?
If you connect to your Dyson device using the Dyson app, would you be able to see those values?

**Comment by jharvey83** [comment]
I don’t think so. I can try upping the log level to see; presumably that’s an MQTT response?

Not sure I follow what you mean on the Dyson app?

**Comment by joe-ng** [comment]
Yup, it's an MQTT response and you should be able to see that with the current log level as it's the same as request for current update entry.

For Dyson app, I was referring to the "Dyson Link" app that was implemented by Dyson. It used the same MQTT query to control the fan.

**Comment by jharvey83** [comment]
Well...this is embarrassing...I'd omitted from the config a valid IP. Oops. My bad!

If I get a chance I'll attempt to create a PR to pattern match, if interested in accepting?

**Comment by joe-ng** [comment]
Sure, feel free to do so.
