### ISSUE TITLE
Heater not showing up in Home app.

### ISSUE THREAD

**Issue by xxKeoxx** [joe-ng/homebridge-dyson-link#11]
I see my dyson heater showing up in the output on homebridge, and I see updates as I change things with my remote, but I don't see the device in the home app.  Any Advice?

**Comment by joe-ng** [comment]
Just to confirm, did you see other things like temperature/humidity sensor in the Home app?

**Comment by drpoutine** [comment]
Hmm I seem to have this problem too.
everything seems to be in order but no heater on the home app

[2/28/2018, 9:03:53 PM] [homebridge-dyson-link.DysonPlatform] Finished launching. Start to create accessory from config

**Comment by xxKeoxx** [comment]
After restarting homebridge multiple times, my devices finally showed up.
