### ISSUE TITLE
RaspberyPi Homebridge - Dyson not appearing in Home app

### ISSUE THREAD

**Issue by cbee69** [joe-ng/homebridge-dyson-link#117]
Hi everyone!

So close to get this working but in Home app when trying to add accessory it refuses to pop up or either it says accessory have already been added.

Logging on Homebridge UI, the log seems fine with no errors and I was able to control Dyson via the accessories section but just can't seem to add this to Home app. Below is my code, am I doing something wrong with the coding? Kinda new to coding stuff so any advise to make this work or to improve it is much appreciated. 

{
    "bridge": {
        "name": "Homebridge xxxxx",
        "username": "xxxxxxxxxx",
        "port": xxxxxx,
        "pin": "xxxxxx"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": xxxxxx,
            "platform": "config"
        },
        {
            "name": "SamsungTizen",
            "devices": [
                {
                    "name": "Living Room TV",
                    "ip": "xxxxxxxxx",
                    "mac": "xxxxxxxxx"
                }
            ],
            "platform": "SamsungTizen"
        },
        {
            "platform": "DysonPlatform",
            "name": "DysonPlatform",
            "email": "xxxxxxxxx",
            "password": "xxxxxxx",
            "country": "xx",
            "accessories": [
                {
                    "ip": "xxxxxxxxxxxxxxx",
                    "displayName": "Master Room Dyson",
                    "serialNumber": "xxxxxxxxxxxxxxxxx"
                }
            ]
        }
    ]
}

**Comment by donavanbecker** [comment]
@cbee69 have you tried this plugin, [homebridge-dyson-pure-cool](https://github.com/lukasroegner/homebridge-dyson-pure-cool)?

**Comment by cbee69** [comment]
> @cbee69 have you tried this plugin, [homebridge-dyson-pure-cool](https://github.com/lukasroegner/homebridge-dyson-pure-cool)?

Hi! Yes I have! Worked well for one day and all of a sudden I’m getting errors in log about unable to login with Dyson username & password. Kinda gave up on that plugin and heard this one was good.

But I don’t mind trying homebridge Dyson pure cool plugin again but did you have any issues with it trying to log into Dyson account before? That plugin seem so easy to use at that time.

**Comment by donavanbecker** [comment]
I know I had that issue before too, but my accessories still worked. I would give it another try. The only reason I say use that one, is because I haven't seen any movement on this plugin since January.

**Comment by cbee69** [comment]
> I know I had that issue before too, but my accessories still worked. I would give it another try. The only reason I say use that one, is because I haven't seen any movement on this plugin since January.

Okay will do! Something I realised just then, since ip address could change due to DHCP on my router I think i will need to reserve that ip address for Dyson, make it permanent and not change or else it will cause problems I think! Will try it tomorrow, thanks for replying!

**Comment by donavanbecker** [comment]
> Okay will do! Something I realised just then, since ip address could change due to DHCP on my router I think i will need to reserve that ip address for Dyson, make it permanent and not change or else it will cause problems I think! Will try it tomorrow, thanks for replying!

Yes i would definitly reserve the IP.

**Comment by cbee69** [comment]
> > Okay will do! Something I realised just then, since ip address could change due to DHCP on my router I think i will need to reserve that ip address for Dyson, make it permanent and not change or else it will cause problems I think! Will try it tomorrow, thanks for replying!
> 
> Yes i would definitly reserve the IP.

Hey I'm getting the same problem again on the homebridge-dyson-pure-cool plugin. Looking at the log it was able to sign in using the credentials and got the Dyson API. However same problem as the other plugin where my Home app can't seem to find the device or Homebridge device. Scanning Homebridge QR code and it says accessories has already been added and when I go to 'i dont have a code or cannot scan' enter in my code but nothing pops up to be added either. I did muck around with Home app alot but I'm pretty sure it has not been added yet and under 'Hubs and bridges' settings the Homebridge device is not listed there. Please help :( 

Below is my code and feel free to give me any tips on how to code it better 👍 

{
    "bridge": {
        "name": "Homebridge xxxxxx",
        "username": "xxxxxxx",
        "port": xxxxx,
        "pin": "xxxxxx"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "SamsungTizen",
            "devices": [
                {
                    "name": "xxxxxxxxx",
                    "ip": "xxxxxxxxxxxxxxxx",
                    "mac": "xxxxxxxxxxxxx"
                }
            ],
            "platform": "SamsungTizen"
        },
        {
            "username": "xxxxxxxxxxxxxxxxx",
            "password": "xxxxxxxxx",
            "countryCode": "xx",
            "devices": [
                {
                    "ipAddress": "xxxxxxxxxxxxxx",
                    "serialNumber": "xxxxxxxxxxxxxxxxx",
                    "enableAutoModeWhenActivating": false,
                    "isNightModeEnabled": true,
                    "isJetFocusEnabled": true,
                    "isTemperatureSensorEnabled": true,
                    "isHumiditySensorEnabled": true,
                    "isAirQualitySensorEnabled": true,
                    "isSingleSensorAccessoryModeEnabled": false,
                    "isSingleAccessoryModeEnabled": false
                }
            ],
            "platform": "DysonPureCoolPlatform"
        }
    ]
}

**Comment by donavanbecker** [comment]
@cbee69 how did you install homebridge?

**Comment by cbee69** [comment]
> @cbee69 how did you install homebridge?

Hey! All good now, I had to google it haha. Basically had to rename the MAC address (username) of bridge code section. I just changed one letter. After restarting Homebridge the device was appearing in Home app! Yay!

**Comment by donavanbecker** [comment]
@cbee69 can we close this?

**Comment by cbee69** [comment]
> @cbee69 can we close this?

Yup for sure! Just want to add one more thing, if your having problems pairing devices with Homekit, the latest HomeBridge version allows an option under 'HomeBridge settings' and under 'reset' that can be useful to try. Cheers!
