### ISSUE TITLE
Feature requested: Filter life

### ISSUE THREAD

**Issue by PParit** [joe-ng/homebridge-dyson-link#12]
May I ask for additional feature? Ability to display filter life in homekit?

**Comment by joe-ng** [comment]
I would love to do that as a Christmas present but unfortunately not, Apple doesn’t support this in the HomeKit API to show this within the Home app.

Have a great Christmas!

**Comment by PParit** [comment]
Thanks for the swift reply. Anyway, your plugin is already working perfect for me.

Have a great Christmas too! :-)

**Comment by leoneleone** [comment]
@joe-ng 

Would you consider adding the two relevant FilterLife Characteristics to the plugin, even though it won't show up in the Home app? 
I believe that even though the Characteristics listed below won't be visible inside the Home app, HomeKit will still send you a notification to change the filter and tell you what the FiletrLife level percentage is currently. This would be very useful to HomeKit users.

I hope you will reconsider adding these Characteristics 🙂 

Any Characteristic can be Added to any Service, HomeKit is agnostic when it comes to Characteristics, and the Characteristics will definitely still function even though you can't see them in Home app.
Just make sure to use .addCharacteristic when defining the Characteristic under Service.Fan

`/**
 * Characteristic "Filter Change Indication"
 */

Characteristic.FilterChangeIndication = function() {
  Characteristic.call(this, 'Filter Change Indication', '000000AC-0000-1000-8000-0026BB765291');
  this.setProps({
    format: Characteristic.Formats.UINT8,
    maxValue: 1,
    minValue: 0,
    validValues: [0,1],
    perms: [Characteristic.Perms.READ, Characteristic.Perms.NOTIFY]
  });
  this.value = this.getDefaultValue();
};

inherits(Characteristic.FilterChangeIndication, Characteristic);

Characteristic.FilterChangeIndication.UUID = '000000AC-0000-1000-8000-0026BB765291';

// The value property of FilterChangeIndication must be one of the following:
Characteristic.FilterChangeIndication.FILTER_OK = 0;
Characteristic.FilterChangeIndication.CHANGE_FILTER = 1;

/**
 * Characteristic "Filter Life Level"
 */

Characteristic.FilterLifeLevel = function() {
  Characteristic.call(this, 'Filter Life Level', '000000AB-0000-1000-8000-0026BB765291');
  this.setProps({
    format: Characteristic.Formats.FLOAT,
    maxValue: 100,
    minValue: 0,
    perms: [Characteristic.Perms.READ, Characteristic.Perms.NOTIFY]
  });
  this.value = this.getDefaultValue();
};

inherits(Characteristic.FilterLifeLevel, Characteristic);

Characteristic.FilterLifeLevel.UUID = '000000AB-0000-1000-8000-0026BB765291';
`

**Comment by joe-ng** [comment]
sure, will check on this

**Comment by joe-ng** [comment]
I have added this to the fan characteristic as well as the filter maintenance service. 
you may try to v1.6 to see if that works for you

**Comment by leoneleone** [comment]
Thanks. Will give it a try. 
Won’t be able to report back until my dyson filter needs to be changed though... but it’s only logical to assume HomeKit will now notify me of that. I’ll try to remember to screencap the notification when it eventually appears for confirmation. 👍🏼
