### ISSUE TITLE
syntax error unexpected token

### ISSUE THREAD

**Issue by rediphone** [joe-ng/homebridge-dyson-link#121]
Hi there, just setting this up from scratch with a fresh install of homebridge and dyson link

have been working to get my fan added and on completing the config i am getting the error below:

[8/15/2020, 13:40:47] Homebridge is running on port 51151.
[8/15/2020, 13:40:47] SyntaxError: Unexpected token e in JSON at position 1
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (C:\<path>\npm\node_modules\homebridge-dyson-link\index.js:179:40)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[8/15/2020, 13:40:47] [HB Supervisor] Homebridge Process Ended. Code: 1, Signal: null

My config file is setup like:
{
    "bridge": {
        "name": "Homebridge FE57",
        "username": "username",
        "port": 51151,
        "pin": "pin"
    },
    "accessories": [],
    "platforms": [
        {
            "platform": "config",
            "name": "Config",
            "port": 8080,
            "sudo": false
        },
        {
            "platform": "DysonPlatform",
            "name": "DysonPlatform",
            "email": "email",
            "password": "password",
            "accessories": [
                {
                    "ip": "ipaddress",
                    "displayName": "fan",
                    "serialNumber": "DYSON-PE9-UK-xxxxxxx-xxx",
                    "password": "password"
                }
            ]
        }
    ]
}

I think thaat everything is setup right, am a bit baffled as to where to go from here. 

i think the issue is around the password field as putting no password in there generates an error advising the password is wrong. entering a password, whatever i put in there (the test password does not start with e) gives me the error show above.

sorry i hope this is something silly im doing? any help would be great

**Comment by donavanbecker** [comment]
[homebridge-dyson-pure-cool](https://github.com/lukasroegner/homebridge-dyson-pure-cool)

**Comment by rediphone** [comment]
> 
> 
> [homebridge-dyson-pure-cool](https://github.com/lukasroegner/homebridge-dyson-pure-cool)

Thank you!
