### ISSUE TITLE
Homebridge fails after updating to 2.5.3

### ISSUE THREAD

**Issue by rummeyer** [joe-ng/homebridge-dyson-link#124]
[19.12.2020, 09:30:13] Error loading platform requested in your config.json at position 4
Dez 19 09:30:13 raspberrypi homebridge[628]: [19.12.2020, 09:30:13] Error: The requested platform 'DysonPlatform' was not registered by any plugin.
Dez 19 09:30:13 raspberrypi homebridge[628]:     at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
Dez 19 09:30:13 raspberrypi homebridge[628]:     at /usr/local/lib/node_modules/homebridge/src/server.ts:387:37
Dez 19 09:30:13 raspberrypi homebridge[628]:     at Array.forEach (<anonymous>)
Dez 19 09:30:13 raspberrypi homebridge[628]:     at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:374:27)
Dez 19 09:30:13 raspberrypi homebridge[628]:     at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:153:29)
Dez 19 09:30:13 raspberrypi homebridge[628]:     at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
Dez 19 09:30:13 raspberrypi homebridge[628]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Dez 19 09:30:13 raspberrypi homebridge[628]:     at Module._compile (internal/modules/cjs/loader.js:1063:30)
Dez 19 09:30:13 raspberrypi homebridge[628]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
Dez 19 09:30:13 raspberrypi homebridge[628]:     at Module.load (internal/modules/cjs/loader.js:928:32)
Dez 19 09:30:13 raspberrypi homebridge[628]: [19.12.2020, 09:30:13] Got SIGTERM, shutting down Homebridge...

**Comment by rummeyer** [comment]
downgraded to 2.5.2 and works fine again

**Comment by joe-ng** [comment]
sorry, was trying to figure out the release using Azure pipeline. just did a 2.5.4 now
let me know if that works for you

**Comment by rummeyer** [comment]
No worries. Thanks for fixing. Works perfectly now.
