### ISSUE TITLE
Feature Requested : Fan V2 accessory 

### ISSUE THREAD

**Issue by gavind87** [joe-ng/homebridge-dyson-link#13]
Can we use the Fan V2 introduced in IOS 11, so that we can integrate the oscillate with the fan speed ?

**Comment by Krocko** [comment]
That would be really cool.

**Comment by joe-ng** [comment]
I seemed to recall there was some limitation in the API that prevented me to use Fan V2.
But let me check that out again in the weekend to confirm this.

**Comment by joe-ng** [comment]
I have changed to use Fan V2 in the latest version, 1.4.x, and it seemed to work fine on my side. (And updated the mqtt dependency to the latest one as Github said there was potential security vulnerability in the old version)

You may try that out when you have a chance.
Let me know if that works for you.

Have a Happy 2018!

**Comment by Krocko** [comment]
Thank you very much for this. That is really cool and works very well.

**Comment by gavind87** [comment]
Looks like it broke something for me...

**Comment by joe-ng** [comment]
Can you elaborate a bit on what was broken?

**Comment by gavind87** [comment]
I was troubleshooting what was wrong with the new package and ended up breaking homebridge completely.. reverting to a backup now. I will revert with my findings after the restore

**Comment by gavind87** [comment]
So I reverted back to a back up, and it still wasn’t responding ( this with the old version 1.3.x ) 

I removed the package and everything back to normal again. So I’m wondering what’s happened that even the old one isn’t working anymore. Mind you before the upgrade it was working fine

**Comment by gavind87** [comment]
reinstalling the latest version, everything in homebridge shows updating, and then after awhile it shows no response. the only way to get things to respond is to remove homebridge-dyson-link and everything works as per normal again

**Comment by gavind87** [comment]
for what its worth, i tried another plugin homebridge-dyson-fan and it also didn't work. I'm getting just MQTT-RECONNECT. seems like the fans have stopped communicating via MQTT after the update and even a rollback doesn't help

**Comment by ifeign** [comment]
Is it possible to use this to add Auto as an option for fan speed? As it stands now, I have auto as a separate switch. Seikan, the developer of homebridge-mi-air-purifier was able to do so with his plugin, though obviously it's an entirely different device/api - all I know is it uses FanV2 as well.

**Comment by joe-ng** [comment]
yes, i have just changed that in the latest version 1.5

**Comment by Krocko** [comment]
How to use that feature? In apples home app the fan is showen as off, if the auto mode is on. In the eve app i can‘t change between manuel mode and auto mode.

**Comment by joe-ng** [comment]
You will need to long/forced press the fan icon in home app(just like how you did for swing) and go to "Details" on the bottom right of the fan and find the auto/manual mode on that page

**Comment by Krocko** [comment]
Yes, i know. But after this the state goes to off.

**Comment by leoneleone** [comment]
That’s because you need to define both Characteristic.TargetFanState and Characteristic.CurrentFanState (one for setCharacteristic and the other for getCharacteristic
Also, Boolean 0 value should be mapped to fmod: “FAN” rather than fmod: “OFF” as it is currently

**Comment by joe-ng** [comment]
Yup, that was a bug for fan state and i have fixed like 15 mins ago and published patch for that. 
thanks for letting me know.

For TargetFanState and CurrentFanState, yes, i think i have set that the get/set function for that

**Comment by Krocko** [comment]
Thank you, for the fast fix.

**Comment by Krocko** [comment]
Any chance to get the current fan speed in Auto modus? The speed, wich is chown in the auto mode ist from the previous manuel mode.

**Comment by joe-ng** [comment]
I found this seemed not to be possible for that because once we set the fan as "Auto", the fan speed will become "Auto" too from Dyson status and we have no way to get the current fan speed.
