### ISSUE TITLE
Could Not Login to Dyson 

### ISSUE THREAD

**Issue by thematthewman** [joe-ng/homebridge-dyson-link#137]
Im on a Dyson DP04 and after restarting my HOOBS system its given me this error. I’ve restarted, uninstalled, done everything I could thing of and nothing seems to help.
`[DysonPlatform] Could not login to Dyson   [DysonPlatform] Missing password for device with serial number VV6-US-NGA1462A, devices found on your account:  `

**Comment by sniereffo** [comment]
I had the same problem and found a remedy that worked, for me and others.  

Log out of the Dyson iOS app and back in. Following that, restart your Homebridge server.
