### ISSUE TITLE
homebridge-dyson-link requires Node version of >=8.0.0

### ISSUE THREAD

**Issue by docteurmicro50** [joe-ng/homebridge-dyson-link#16]
Hi,

According to my raspeberry pi 1 B hardware I'm using node version of v6.12.3, so I have the following message at homebridge start : 

Plugin /opt/node/lib/node_modules/homebridge-dyson-link requires Node version of >=8.0.0 which does not satisfy the current Node version of v6.12.3. You may need to upgrade your installation of Node.

But It seems that the plugin is starting well but not working from the home app :

Feb 02 09:37:12 raspberrypi homebridge[4815]: [2/2/2018, 9:37:12 AM] [DysonPlatform] Finished launching. Start to create accessory from config
Feb 02 09:37:12 raspberrypi homebridge[4815]: [2/2/2018, 9:37:12 AM] [DysonPlatform] Dyson IP:192.168.97.114 Serial Number:DYSON-PT4-EU-HGA0393A-455
Feb 02 09:37:17 raspberrypi homebridge[4815]: [2/2/2018, 9:37:17 AM] [DysonPlatform] Air Quality Sensitivity (Default is 1): 1
Feb 02 09:37:17 raspberrypi homebridge[4815]: [2/2/2018, 9:37:17 AM] [DysonPlatform] Device serial number format valids
Feb 02 09:37:17 raspberrypi homebridge[4815]: [2/2/2018, 9:37:17 AM] [DysonPlatform] Device not cached. Create a new one
Feb 02 09:37:17 raspberrypi homebridge[4815]: [2/2/2018, 9:37:17 AM] [DysonPlatform] Init Sensor for Dyson
Feb 02 09:37:17 raspberrypi homebridge[4815]: [2/2/2018, 9:37:17 AM] [DysonPlatform] Init Fan State for Dyson
Feb 02 09:37:17 raspberrypi homebridge[4815]: [2/2/2018, 9:37:17 AM] [DysonPlatform] Heat Available. Add Heat button and jet control

Could you tell me node upgrade to 8+ is mandatory and if it this reason why command from home app is not working?

Thanks.

Julien R.

**Comment by joe-ng** [comment]
Did you see the log about "[DysonPlatform] Connected to PT4-EU-HGA0393A"?
If not, that means the communication between your fan and the plugin was not set up and it might be because
i) the IP 192.168.97.114 is not correct or is blocked by your router
ii) mqtt package does not work correctly in your node
