### ISSUE TITLE
Problem with multiple hombridge instances

### ISSUE THREAD

**Issue by Krocko** [joe-ng/homebridge-dyson-link#17]
I use this plugin in the first instance. If i create a second hombridge instance, the plugin tryes to load the infos from the config.json. I think, it is similar to this  https://github.com/nfarina/homebridge/issues/1160 have you a solution for this?

**Comment by joe-ng** [comment]
hmm... I am not sure if I can do anything for this because the plugin just reads the config given by homebridge. So it's up to homebridge to decide how it reads the config file.

**Comment by Krocko** [comment]
But if i start a second homebridge instance with a different path for the config.json and no dyson accessories in it, the plugin regardless tries to load the dyson device. Other plugins don‘t do this.

**Comment by joe-ng** [comment]
Thanks for the log, I think i may be able to fix this then. 
Will let you know once I have a patch for this.

**Comment by Krocko** [comment]
Thank you very much for your work.

**Comment by joe-ng** [comment]
Just tried to fix that, when you have a chance, you may try the v1.7 for that

**Comment by Krocko** [comment]
Works now! Thank you very very much!
