### ISSUE TITLE
Auto mode not updating status in home app

### ISSUE THREAD

**Issue by aleszczynskig** [joe-ng/homebridge-dyson-link#18]
If our Fan is in auto mode. The home app does not update to reflect the state of the fan (speed etc). In fact any change made using the remote does not seem to update in home app. Is this is the correct behaviour?

Thanks

**Comment by joe-ng** [comment]
Yes, this is the "expected" behavior because once it's set in Auto mode, it would no longer publish its fan speed in the MQTT query and it would just mention "AUTO" in the speed.
