### ISSUE TITLE
Pure Cool Auto setting not sticking when triggered by scenes

### ISSUE THREAD

**Issue by gabemunro** [joe-ng/homebridge-dyson-link#21]
First off, thank you, this is great and I genuinely appreciate the work you've put into it. 

I'm running into a problem with the new fan control after updating to 1.7 (from 1.3), where trying to set a fan to auto mode using a HomeKit scene will briefly set the Pure Cool to auto mode at speed 4 (like it usually starts at in auto mode), but then after a half second auto mode deactivates and it remains at speed 4. I've attached a chunk of my Homebridge log where it was doing it. During this timeframe in the log, the device was controlled exclusively by the Home app, and not the Dyson Link app, the remote, or any scheduled activity.

Thanks!

[homebridge.log](https://github.com/joe-ng/homebridge-dyson-link/files/1737302/homebridge.log)

**Comment by tijunoi** [comment]
Hey, is there any news about this? I'm having the same issue with all the scenes. Is there any way to intercept the change in the homebridge plugin and not actually send the command to the dyson?

**Comment by joe-ng** [comment]
it seemed that there was some issue with the FanV2 on how it stores and sets the Auto/Manual mode.
I have moved the auto mode back as separate switch for now for Dyson cool device in v1.8 and you may try if that works for you
