### ISSUE TITLE
Appending the sample config.json

### ISSUE THREAD

**Issue by nwoodman** [joe-ng/homebridge-dyson-link#24]
Hi not really an issue as such  more an issue at my end.  I would love to append the following to the json.config file.  I have the plugin installed and would like to append the weather accessory to my config.json.  However I have difficulty given that dyson-link code has the accessory embedded in the platform.  Is there a way that I can embed this

{
      				"accessory": "Weather",
      				"apikey": "b6e771a11186cdadd3b5cc3f880eef39",
      				"locationByCoordinates":"lat=-37.000&lon=145.000",
      				"name": "OpenWeatherMap Temperature"
   				 }

into this

{
	"bridge": {
	"name": "Test Homebridge",
        "username": "CC:22:3D:E3:CE:29",
        "port": 51826,
        "pin": "031-45-159"

	},
	"description": "HomeBridge HTTP Status Control",
		"platforms": [{
		"platform": "DysonPlatform",
		"name": "DysonPlatform",
		"accessories": [
				{
				"ip": "192.168.0.66",
				"displayName": "DYSON FAN",
				"serialNumber": "DYSON-SW4-AU-JKA0755A-469",
				"password": "kdkvrcrb",
				"sensitivity": 1
				}
				
						]
	}]
}

**Comment by joe-ng** [comment]
I think they should be put in different objects like below


{
"bridge": {
"name": "Test Homebridge",
"username": "CC:22:3D:E3:CE:29",
"port": 51826,
"pin": "031-45-159"

},
"description": "HomeBridge HTTP Status Control",

"accessories": [{
"accessory": "Weather",
"apikey": "b6e771a11186cdadd3b5cc3f880eef39",
"locationByCoordinates":"lat=-37.000&lon=145.000",
"name": "OpenWeatherMap Temperature"
}],

	"platforms": [{
	"platform": "DysonPlatform",
	"name": "DysonPlatform",
	"accessories": [
			{
			"ip": "192.168.0.66",
			"displayName": "DYSON FAN",
			"serialNumber": "DYSON-SW4-AU-JKA0755A-469",
			"password": "kdkvrcrb",
			"sensitivity": 1
			}
			
					]
}]
}
