### ISSUE TITLE
1.7

### ISSUE THREAD

**Issue by ddorato** [joe-ng/homebridge-dyson-link#25]
Anyone noticing that in 1.7 HomeBridge hangs when viewing a Dyson-Link accessory?

**Comment by leoneleone** [comment]
Same here. Intermittent “no response” from my dyson fans. Other devices on the same homebridge setup not experiencing the same. 
I suspect this is something happening on the dyson link server end. Not sure of course, but my iOS dyson link app has been updated quite a few times in the passed month or so.

**Comment by ddorato** [comment]
Its weird because I see the responses in the Homebridge CLI, but when actually using the app.  Crash city and "no responses"

**Comment by leoneleone** [comment]
Could just be a problem in the Home.app itself. 
What iOS version are you on? 
I’m on 11.3 beta 4, so can’t really be sure it’s not my version of Home.app

**Comment by ddorato** [comment]
I've tested a few versions... This problem specifically happened when I updated to 1.7 and updated NPM.
