### ISSUE TITLE
"Incorrect serial number" on 2018 Dyson Pure Cool Tower

### ISSUE THREAD

**Issue by proxycheck** [joe-ng/homebridge-dyson-link#28]
On the latest Dyson Pure Cool Tower, model number TP04 it gives the following error:

`[DysonPlatform] Finished launching. Start to create accessory from config`
`[DysonPlatform] Dyson Pure Cool Tower IP:192.168.0.40 Serial Number:DYSON-HIDDEN`
`[DysonPlatform] Incorrect serial number `

I suspect this is because the new TP04 doesn't have a password that I can give? - On the bottom of the unit and the manual only display a serial number and no WiFi password because these appear to use Bluetooth or NFC for initial setup and not WiFi.

I tried putting the WiFi password from my home network in the password field instead, that doesn't work (was a long shot anyway). Any ideas to get it working?

Thanks.

**Comment by AndrewCMartin** [comment]
#32 Support added in this pull request. Now you can leave out the accessory's password field and add your Dyson email and password to the platform config, (or environment variables), and it should retrieve the credentials for the device.
