### ISSUE TITLE
New DP04 no wifi password

### ISSUE THREAD

**Issue by seoulfully** [joe-ng/homebridge-dyson-link#29]
The new DP04 Pure Cool Purifying Fan doesn't have a wifi password (also confirmed with Dyson support).  It does have an eight digit (1234:5678) "access" number to add the device to the Dyson Link app manually if the linking process doesn't work.  Any thoughts on how to get it working with this homebridge plugin?

**Comment by proxycheck** [comment]
Same issue as I am having here: https://github.com/joe-ng/homebridge-dyson-link/issues/28

Hope we can figure out a solution. I also just found the eight digit access number within the filter housing on the device but that doesn't work as a password in the homebridge plugin unfortunately.

**Comment by joe-ng** [comment]
sorry, i don't have that device and am not sure how that works currently.
will need to spend some time to look into that

**Comment by seoulfully** [comment]
Well I’m not super technical, but if you provide instructions I can try stuff for you, etc. if it helps.

Eugene

**Comment by arm22** [comment]
Same here, I have the new TP04 (Dyson Pure Cool Link Purifier).

Looking at the code, it looks like an initial problem is that you're verifying the format of the serial number with a regular expression, but my SN doesn't look like this `DYSON-XXX-XX-XXXXXXXX-XXX` its `XXX-XX-XXXXXXXX`

https://github.com/joe-ng/homebridge-dyson-link/blob/master/DysonLinkDevice.js#L19

**Comment by AndrewCMartin** [comment]
I had this same issue, and after a couple changes to the code I was able to get the fan to connect properly. 

Dyson made a few changes in the format of the messages, but those were pretty straightforward to adjust. E.g. The property "fmod" (mode) which had "AUTO" / "FAN" / "HEAT" options was replaced by "fpwr": "ON" / "OFF" and "auto": "ON"/ "OFF".

The trickier problem was getting the right credentials without the built-in wifi pass like the old models. I found a solution by looking into [this python library (libpurecoollink)](https://github.com/CharlesBlonde/libpurecoollink) which allows users to login with their Dyson account to get the appropriate password for communicating with the fan. 

I've got mine setup by storing the password hash from that program, but I can add in that functionality with the other necessary changes for supporting the TP04 model and submit a pull request. 

If anyone wants to see an example of the messages from the TP04, I've added a few[ here.](https://pastebin.com/aVxiYvBD)

**Comment by AndrewCMartin** [comment]
#32 Pull request added!

**Comment by joe-ng** [comment]
Thanks a lot! 
I just released v2.0 for this

**Comment by seoulfully** [comment]
Man, that was quick. Awesome! Thanks. Installed this morning. Set up config with my username/password, IP address, and serial. When restarting homebridge, the fan shows up as an occupancy sensor with the platform name. And when I manually turn on the fan, it doesn’t trip the occupancy sensor (thought maybe it would trigger if the fan was actively being used). Thoughts?

**Comment by proxycheck** [comment]
It works great for me with my TP04. Thank you so much, even Siri fully understands how to use the fan!

**Comment by seoulfully** [comment]
Wouldn’t see what/why, but wonder if it’s something different about the DP04.

**Comment by seoulfully** [comment]
Nevermind. My config was messed up. Got all sorts of Dyson options. Of course now all homebridge accessories give “no response”. Haha.

**Comment by ayn** [comment]
FYI the [`model`](https://github.com/joe-ng/homebridge-dyson-link/blob/master/DysonLinkDevice.js#L45) for the `DP04` is `520` instead of `438` (which I guess is the `TP04`).
