### ISSUE TITLE
Dyson devices stop reacting, but no others have

### ISSUE THREAD

**Issue by gabemunro** [joe-ng/homebridge-dyson-link#3]
First off, thank you for this. It's exactly what I was hoping to find. Your work is greatly appreciated. I'm experiencing some weird behavior with it though, and am wondering if you have any ideas. 

The two PureCool devices I have connected worked for a while, but then they just stopped. It isn't the usual manner in which homebridge accessories die, where I get a "No Response" error in the home app or something similar. The Home app shows that it is interacting with the device just fine, but there is no reaction from them. For example, I'll turn the fan on to 100%, but it doesn't react, it just sits there in its previous state. When I look it up in the log (admittedly just the standard log, not debug), it shows no status changes or requests.

When it is working fine, the standard log usually shows the activity. Now, nothing. I've tried unplugging and plugging back in the devices to restart them, restarting the iMac that homebridge is running on (it shows it initializing the Dyson devices just fine), restarting the iPhone I'm using to control it all, and nothing.

Since I have several other devices connected through homebridge, I'm hoping that there might be another troubleshooting step other than deleting /accessories, /persist, and re-adding the homebridge device to HomeKit, as it's kinda a pain in the ass to reconfig the accessories and scenes.

Any insight would be greatly appreciated! Again, thanks for your time on this.

**Comment by gabemunro** [comment]
Oh, some other info that may be helpful/relevant:

Node v. 8.2.0
2017 iMac running macOS 10.12.6

+-- homebridge@0.4.22
+-- homebridge-dyson-link@1.1.2
+-- homebridge-harmonyhub@0.2.0
+-- homebridge-nest@1.1.2
+-- homebridge-weather-station-extended@0.1.1
`-- npm@5.3.0

**Comment by Krocko** [comment]
Please look in issue #2. I think you have the same Problem.

Try the following:
stop homebridge
delete the "cachedAccessories" file
and restart homebridge.

**Comment by gabemunro** [comment]
Ahhh crap. You were right. I could have sworn that I already read through that one. Sorry!
