### ISSUE TITLE
Auto mode not being set reliably when turning on

### ISSUE THREAD

**Issue by SteveIsles** [joe-ng/homebridge-dyson-link#38]
I tried to create a scene specifying that the auto mode switch be turned on, and it seems to not respect that: the "A" on the bottom of the fan doesn't come on.  I believe that if the fan was previously off, the setting of the fan speed to whatever is in the scene (in my test scene 10%) when the fan receives the 10% and auto switch, the auto setting gets turned off.

Is there a way to send API commands so that Auto is "re-applied" if it is on in the HomeKit settings?  Otherwise, there is no way to reliably enable auto.

BTW: I have a mixture of the non-2018 cool+hot fan and the cool tower.  Both have different ways of turning on Auto vs. Manual (I am still not sure why in one case it is a switch and the other it is a "detail") but neither work properly nor consistently.

If after the fact I go turn on auto or turn on off auto only but not change the oscillate setting or speed setting I can change the auto status, but as such, there is no way to turn on a scene involving the fans and have the auto status set reliably...

**Comment by joe-ng** [comment]
yup, i understood what you meant but this seemed to be limitation of a scene setting that we could not control the order.
however, as a workaround, i think we can do that that by setting the "Auto" switch to "On" on the scene without setting the fan to "On". in this way, the fan will still be turned on with "Auto" set.
