### ISSUE TITLE
Error loading DysonLink Plugin

### ISSUE THREAD

**Issue by DerEarl88** [joe-ng/homebridge-dyson-link#4]
![img_0740](https://user-images.githubusercontent.com/30392463/28501974-6d4be0d4-6fe8-11e7-889d-b41d1dca950c.PNG)

I got the following error after installing your homebridge-dysonlink plugin. I have updated node and npm and your plugin. I hope you can help me. I am trying for many hours but could not resolve the problem.

Thanks a lot.

Best greetings from Germany

Dirk

**Comment by joe-ng** [comment]
Which version of Node.js are you using?
From the error log, it seemed that it didn't support the latest version of JavaScript(ES 6)
Can you try to update that to latest version?
