### ISSUE TITLE
Provide separate values for Air Quality, PM2.5 and PM10

### ISSUE THREAD

**Issue by mguntli** [joe-ng/homebridge-dyson-link#43]
The current code performs an average of VOC and dust level to calculate the air quality:
https://github.com/joe-ng/homebridge-dyson-link/blob/master/DysonEnvironmentState.js#L21

In the current HomeKit Accessory Protocol there exist more characteristics:
- Air Quality (=VOC level)
https://developer.apple.com/documentation/homekit/hmcharacteristicvalueairquality
- Air Particluate Density in micrograms/m^2 (for PM2.5 and PM10)
https://developer.apple.com/documentation/homekit/hmcharacteristicvalueairparticulatesize

**Comment by martinzuern** [comment]
This would be great indeed. 
There seems to be a characteristic for VOCs (besides the overall air quality) as well.
