### ISSUE TITLE
Air Quality not displayed in notification

### ISSUE THREAD

**Issue by Ribero** [joe-ng/homebridge-dyson-link#44]
Hi,

Everything works like a charm with a Dyson Cool+Hot Link Thanks so much, amazing work !!

I'm just wondering why I can see "Air Quality" in Apple Home "Favorites" but not in the "Notification" area of the application (please see screen capture).
![img_b6f6aff15b56-1](https://user-images.githubusercontent.com/2266264/42411701-7b8b2b34-8200-11e8-823c-d1ab811b1464.jpeg)

**Comment by seoulfully** [comment]
@ribero, I don’t have a solution, but what number are you using for the air quality sensitivity in your config? I can never seem to get mine to show anything but poor. Every now and then it’ll get to good. The Dyson app itself has my air quality consistently good.

**Comment by Ribero** [comment]
The air quality reported seems to be accurate and correspond with the real value returned by Dyson Fan. In the screen capture it reports an "Excellente" (french) which mean Excellent in english.

I do not understand why this "button" is always grayed out even if it seems to work and report correcte values...

**Comment by joe-ng** [comment]
> I do not understand why this "button" is always grayed out even if it seems to work and report correcte values...

as far as i know, it seemed to be the display design/limitation from the Home app and we have no control for this unfortunately 
same thing for the notification status.
