### ISSUE TITLE
Enhancements to air quality sensor and rotation speed step

### ISSUE THREAD

**Issue by lukasroegner** [joe-ng/homebridge-dyson-link#53]
Hi Joe!

First of all, thank you for putting so much effort in this project. 

As the Dyson devices only have 10 steps for fan speed, I forked your project and added the "minStep" property to the fans. Moreover, there are properties for the air quality sensor like PM2.5, PM10, VOC and NO2, which I also integrated (#43). I also added the device information to the accessories (#40) Finally, there seemed to be issues (#49) with setting the rotation speed (which is due to the fact, that the home app sets the "Active" characteristic to "On" every time you change the rotation speed), which is have solved.

I also took a quick look at the calculation for the air quality (#46) and tried to enhance the algorithm. I'm not using the "Auto" mode, so I added the property "autoModeVisible" to the configuration.

If you would like me to create a pull request (and you have time for a code review), feel free to ask me.
I own the latest Pure Cool tower and table fans, however, I don't have access to the older models to provide better support.

Best regards
Lukas

**Comment by antiabed** [comment]
I need this so badly! Will it be a lot of work still for the plugin developer to incorporate a forked version back into the master?

**Comment by lukasroegner** [comment]
This is super simple! I create a pull request to merge changes into the master, the owner just has to accept the changes.

If you want to try out my version, you can take a look at the README and even install it with npm (using the git URL) on your device.

**Comment by joe-ng** [comment]
Thanks a lot on doing this!
I have been out of the country for business and personal trips and didn’t have a chance to check on this project recently.
If you can create a pull request for this, I will merge this in the weekend.

**Comment by antiabed** [comment]
Awesome! Thank you both for the great work. I’ll wait for the merge.

**Comment by lukasroegner** [comment]
Created the pull request: #55

**Comment by joe-ng** [comment]
I have just merged that and published a new version.
Thanks for your help!

**Comment by lukasroegner** [comment]
Thank you for merging the PR!

**Comment by lukasroegner** [comment]
@joe-ng Can you close the issues I referenced in my first comment? Thanks again!
