### ISSUE TITLE
Will it work if homebridge is not on the same network as the Dyson fan?

### ISSUE THREAD

**Issue by paolotremadio** [joe-ng/homebridge-dyson-link#59]
Hi,

I'm running my Dyson fan on a different wifi/network from the home network (where I'm running homebridge). The two networks are totally isolated and cannot communicate with each other. I've noticed that I can still use the dyson app and the fan is super quick in responding (as both my phone and the dyson are connected to the internet). 

Will this plugin work in this setup or I have to somehow bridge the two networks? I'm more than  happy to accept a slightly delay  in response (due to the need of connecting via the dyson servers).

Cheers

**Comment by joe-ng** [comment]
I think it won’t work unfortunately because it is the homebridge to send request to Dyson device directly using the IP it got. So unless homebridge can access the IP of Dyson device, it would not be able to communicate with your device
