### ISSUE TITLE
no feedback on actual speed in AUTO

### ISSUE THREAD

**Issue by paqpaqpaq** [joe-ng/homebridge-dyson-link#64]
When the dyson DP04 is on AUTO (which it is) it doesn;t send any feedback on the actual speed. The plugin simply claims it is 50% (always)
But 50% is like setting 6, en at "idle" speed it is running at approx setting 2 in the dyson app.

Can this be updated as accordingly with the changes on the dyson itself?

**Comment by joe-ng** [comment]
i am afraid not as the device didn't provide its speed in auto mode in the MQTT message
