### ISSUE TITLE
Plugin makes HomeBridge unresponsive if fan is not connected

### ISSUE THREAD

**Issue by lin714093880** [joe-ng/homebridge-dyson-link#88]
If this plugin can’t connect with the Dyson fan, it  makes the whole HomeBridge unresponsive. Not only the fan but also other HomeBridge-controlled devices in HomeBridge won’t respond to the Home app.

**Comment by Hucksleyy91** [comment]
I have that issue with some accessories and there is a simple fix create another homebridge instance and just put that accessory in there I use a app currently in beta atm called Homemanager on iOS

**Comment by alexlijw** [comment]
Hey guys, I used to experience the same issue. But I just tried to put dyson at the first place in the platform, then it works! 



`    "platforms": [
        {
            "platform": "DysonPlatform",
            "name": "DysonPlatform",
            "email": "xx@gmail.com",
            "password": "xxxxx",
            "accessories": [
                {
                    "ip": "192.168.2.56",
                    "displayName": "dyson",
                    "serialNumber": "DYSON-PT4-EU-xxx-455",
                    "password": "xx",
                    "autoModeVisible": false,
                    "nightModeVisible": false,
                    "focusModeVisible": true
                }
            ]
        }, //then come other equipment.
        {
            "platform": "Hue",
            "users": { `

**Comment by jasper-seinhorst** [comment]
I've had this issue multiple times. Your dysons ip adres probably changed or was not responding for a while. Turn of your dyson 10 seconds (unplug from wall) and restart your homebridge instance should "fix" your problem.

If that doesn't work try to restart your router when you turn off your dyson.

**Comment by PrzemyslawKlys** [comment]
@jasper-seinhorst it's not about IP changing. It's about disconnecting Dyson from Power. My girlfriend sometimes disconnects Dyson to connect other device and while it's disconnected whole home bridge hangs so any other device is uncontrollable. It would be cool to have a fix for this.

**Comment by afrustagli** [comment]
Unfortunately, this part of Homebridge's current architecture. If one plugin is unresponsive the entire instance of Homebridge is unresponsive. The solution is to start a separate Homebridge instance for each plugin/device. I have 7 instances running, and if any device is unresponsive everything else continues to function.

It's no use registering issues with the individual plugins. This is something that has to change in Homebridge itself. I believe it's on their roadmap, or at least was talked about a while back.

**Comment by ericcastro** [comment]
@afrustagli not true. I have other homebridge devices that I can disconnect entirely and won't affect the others (example homebridge-mqtt)

**Comment by ifeign** [comment]
This is a major flaw with this plugin, @afrustagli is incorrect, as every other plugin I use is able to fail gracefully. @joe-ng please take a look at this, it is probably the most urgent issue with this plugin

**Comment by robertgranholm** [comment]
+1 for this issue, if the fan isn't on...all of homebridge goes unresponsive...bummer! 

Any feedback on @afrustagli if/when this will be fixed? Thank you!

**Comment by robertgranholm** [comment]
Any feedback or way to fix this?

**Comment by lin714093880** [comment]
Guys so I eventually did some debugging myself and the problem is pretty simple, the plugin is missing a check for fan connected in `isNightMode`. 

I patched that and it now seems to work just fine. https://github.com/joe-ng/homebridge-dyson-link/pull/94

**Comment by ericcastro** [comment]
Thank you so much for taking a look. I will try this ASAP and come back with a confirmation that it works
