### ISSUE TITLE
Can not display temperature/humidity

### ISSUE THREAD

**Issue by PParit** [joe-ng/homebridge-dyson-link#9]
May I ask for your help? 
I did install and config everything as instructed in your sample. I'm able to control my dyson fan but the display of the temperature and humidity showed only 0 . Is there any way to correct this issue?
Thank you.

![image-1](https://user-images.githubusercontent.com/29161599/32406474-955567c0-c1ab-11e7-87dd-ba07d0bfae13.jpg)

**Comment by joe-ng** [comment]
Happy to help. As I don't see the same issue from my side, can you start with checking on your Dyson app to see if you saw those values? Sometimes, I found that the Dyson device would return no value for that.
If you can that from the Dyson app, can you send me the log you had for the plugin?
You should be able to see something like
<timestamp> [DysonPlatform] {"msg":"ENVIRONMENTAL-CURRENT-SENSOR-DATA" ....
and 
<timestamp> [DysonPlatform] <device name> - temperature

**Comment by PParit** [comment]
Thank your for your help and sorry for late reply. I just got back from my vacation so I could try what you suggested. Everything after I did restart Dyson device and do config on continuous monitoring went fine. Homekit could read the value from dyson device.

Thanks again for your help.
